PROGRAM STATS
VAR
	SUM,PRODUCT,SUMSQ,I,VALUE,MEAN,VARIANCE,I : INTEGER
BEGIN
	SUM := 0;
	PRODUCT := 0.0;
	SUMSQ := 0;
	FOR I := 1 TO 100 DO
	BEGIN
		READ(VALUE);
		TEMP := 0;
		SUM := SUM + VALUE;
		SUMSQ := SUMSQ + VALUE * VALUE
	END;
	MEAN := SUM DIV 100;
	VARIANCE := SUMSQ DIV 100 - MEAN * MEAN;
	WRITE(MEAN,VARIANCE)&
END.
